### ISSUE TITLE
Does not compile with kernel 4.1.5 (kcl_acpi)

### ISSUE THREAD

**Issue by gl-bars** [kolasa/fglrx-13.101#1]
Build fails with the following error:

```
/lib/modules/fglrx/build_mod/2.6.x/kcl_acpi.c: In function 'KCL_ACPI_GetHandles':
/lib/modules/fglrx/build_mod/2.6.x/kcl_acpi.c:799:49: error: 'struct device' has no member named 'acpi_node'
```

**Comment by gl-bars** [comment]
My bad, I was actually using legacy catalyst 13.1 (solved by compiling catalyst-hd234k from ArchLinux)
